"use strict";

const { fetchJson } = require("../_lib/fetch-json");
const { methodNotAllowed, parseJsonBody, sendJson } = require("../_lib/http");

module.exports = async (req, res) => {
  if (req.method !== "POST") return methodNotAllowed(res, "POST");

  const token = process.env.GITHUB_TOKEN;
  if (!token) return sendJson(res, 500, { error: "GITHUB_TOKEN is not configured." });

  const body = parseJsonBody(req);
  const repoName = String(body.repoName || "").trim();
  if (!repoName) return sendJson(res, 400, { error: "repoName is required." });

  const payload = {
    name: repoName,
    description: String(body.description || "Website generated by Solopilot"),
    private: Boolean(body.private),
    auto_init: true,
  };

  const create = await fetchJson("https://api.github.com/user/repos", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "User-Agent": "solopilot-site",
      "content-type": "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!create.ok) {
    return sendJson(res, create.status, {
      error: "GitHub repo creation failed.",
      details: create.body,
    });
  }

  return sendJson(res, 200, {
    ok: true,
    repo: {
      id: create.body.id,
      name: create.body.name,
      fullName: create.body.full_name,
      url: create.body.html_url,
      cloneUrl: create.body.clone_url,
    },
  });
};
